# Dependencies
markdown:         redcarpet
highlighter:      rougue

# Permalinks
permalink:        pretty

# Setup
title:            HakaseLabs
tagline:          'Endless possiblities through tech.'
description:      'Titles on Software Development, and everything-in-between. All articles are written by Francis Sunday, Software Developer and Tech Enthusiast .'
url:              https://hakaselabs.github.io
baseurl:          /

author:
  name:           'Francis Sunday'
  url:            https://codehakase.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/HakaseLabs/hakaselabs.github.io

gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag

twitter:
  username: codehakase
social: 
  name: Francis Sunday
  links:
    - https://twitter.com/codehakase
    - https://facebook.com/codehakase
    - https://medium.com/@codehakase
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/bg.jpg